name: Label Flaky Test Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  label:
    if: github.event.label.name == 'flaky-test'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Extract labels
        id: extract-label
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          declare -A platform2label

          platform2label["AIX"]="aix";
          platform2label["FreeBSD"]="freebsd";
          platform2label["Linux ARM64"]="linux";
          platform2label["Linux ARMv7"]="arm";
          platform2label["Linux PPC64LE"]="ppc";
          platform2label["Linux s390x"]="s390";
          platform2label["Linux x64"]="linux";
          platform2label["macOS ARM64"]="macos";
          platform2label["macOS x64"]="macos";
          platform2label["SmartOS"]="smartos";
          platform2label["Windows"]="windows";

          # sed is cleaning up the edges
          PLATFORMS=$(echo $BODY | sed 's/^.*Platform\\n\\n//' | sed 's/\(, Other\)\?\\n\\n.*$//') 2> /dev/null
          readarray -d , -t list <<< "$PLATFORMS"
          labels=
          for row in "${list[@]}"; do \
            platform=$(echo $row | xargs); \
            labels="${labels},${platform2label[$platform]}"; \
          done;

          echo '::set-output name=LABELS::$labels'

      - name: Add labels
        uses: andymckay/labeler@master
        with:
          add-labels: "${{ steps.extract-labels.outputs.LABELS }}"
