name: Label Flaky Test Issues

on:
  issues:
    types: [opened, labeled]

jobs:
  label:
    if: github.event.label.name == 'flaky-test'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Echo github obj
        run: echo ${{ toJson(github) }}
